[package]
name = "project"
version = "0.1.0"
authors = ["Adam Vandolder <adam.vandolder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
itertools = "0.9"
rand = "0.7"
